# Generated by Django 2.0.4 on 2018-04-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('birthday', models.CharField(blank=True, max_length=200, null=True)),
                ('town', models.CharField(blank=True, max_length=400, null=True)),
                ('address', models.CharField(blank=True, max_length=400, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('homephone', models.CharField(blank=True, max_length=200, null=True)),
                ('cellphone', models.CharField(blank=True, max_length=200, null=True)),
                ('hobbies', models.CharField(blank=True, max_length=1500, null=True)),
                ('canhelp', models.CharField(blank=True, max_length=1500, null=True)),
                ('needhelp', models.CharField(blank=True, max_length=1500, null=True)),
                ('comments', models.TextField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
    ]
