# Generated by Django 2.0.4 on 2018-07-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='members/'),
        ),
    ]
