# Generated by Django 2.0.4 on 2018-04-27 22:55

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('pub_date', models.DateField()),
                ('newstype', model_utils.fields.StatusField(choices=[('news', 'news'), ('membernews', 'membernews')], default='news', max_length=100, no_check_for_status=True)),
            ],
            options={
                'verbose_name_plural': 'News Entries',
            },
        ),
    ]
