# Generated by Django 2.0.4 on 2018-05-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsentry_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsentry',
            name='header_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
